/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sinup_window.java
 *
 * Created on May 6, 2011, 10:56:41 AM
 */
package cybercenter;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Md. Hasibur Rashid
 */
public class Sinup_window extends javax.swing.JFrame {

    /** Creates new form Sinup_window */
    public Sinup_window() {
        initComponents();
        if (new Login().com_language.getSelectedIndex() == 0) {
            this.bangla_sinup();
        }
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screen.width - 500) / 2, (screen.height - 350) / 2);

        setDefaultLookAndFeelDecorated(true);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User sinup window");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage("Icon\\cybercenter5.png"));
        setResizable(false);

        jLabel1.setText("User name");

        jLabel3.setText("Password");

        jLabel4.setText("Confirm password");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Enterprise", 0, 36));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mastermind  Cyber Center");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cybercenter/Resource/HP-Monitor (Custom).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Come with upcoming cyber world on your new vision");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("©");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel9)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jButton1.setText("Sign in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("All rights are reserved by Mastermind Technology©");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cybercenter/Resource/folder_customer_512 (Custom).png"))); // NOI18N

        jLabel2.setText("Security code");

        jButton3.setText("Delete user");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(83, 83, 83)
                .addComponent(jLabel8)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String str1 = null;
    String str2 = null;
    String str3 = null;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new Login().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void hasib() {

        String usname = jTextField1.getText();


        Connection con = null;
        ResultSet resultSet = null;
        Statement statement = null;
        String url = "jdbc:mysql://localhost:3306/";
        String db = "cyber_center";
        String driver = "com.mysql.jdbc.Driver";
        String users = "root";
        String pass = "";



        try {
            Class.forName(driver);
            con = (Connection) DriverManager.getConnection(url + db, users, pass);
            PreparedStatement st = (PreparedStatement) con.prepareStatement("select * from login where username=?");
            st.setString(1, usname);

            resultSet = st.executeQuery();
            // "SELECT * FROM login where username ='" + usname + "'");
            while (resultSet.next()) {
                str1 = "" + resultSet.getString(1);
                str2 = "" + resultSet.getString(2);
                str3 = "" + resultSet.getString(3);
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error");

        }

    }

    public void login_Database() {
        Connection con;
        Statement statement;
        // ResultSet resultSet;
        //ResultSetMetaData metaData;
        String url = "jdbc:mysql://localhost/mysql";
        // String db = "cyber_center";
        String driver = "com.mysql.jdbc.Driver";
        String user = "root";
        String pass = "";


        try {
            Class.forName(driver);
            con = (Connection) DriverManager.getConnection(url, user, pass);
            statement = (Statement) con.createStatement();


            try {

                statement.executeUpdate("CREATE DATABASE if not exists `cyber_center`");
                //JOptionPane.showMessageDialog(null,"Created");
                //con = (Connection) DriverManager.getConnection(url + db, user, pass);
                url = "jdbc:mysql://localhost/cyber_center";
                con = (Connection) DriverManager.getConnection(url, "root", "");

                statement = (Statement) con.createStatement();
                String table_login = "CREATE TABLE login (username VARCHAR(100) NOT NULL, password VARCHAR(100) NOT NULL, con_password VARCHAR(100) NOT NULL, PRIMARY KEY (username))";

                statement.executeUpdate(table_login);


                con.close();
            } catch (SQLException s) {
                System.out.println("Table is all ready exists!");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error");
            e.printStackTrace();

        }


    }

    public void bangla_sinup() {
        jLabel1.setText("ব্যাবহার কারির নাম ");
        jLabel1.setFont(new java.awt.Font("SolaimanLipi", 0, 11));

        jLabel3.setText("পাসওয়ার্ড ");
        jLabel3.setFont(new java.awt.Font("SolaimanLipi", 0, 11));

        jLabel4.setText("পাসওয়ার্ড নিশ্চিৎ করণ ");
        jLabel4.setFont(new java.awt.Font("SolaimanLipi", 0, 11));
        jLabel2.setText("সুরক্ষা কোড");
        jLabel2.setFont(new java.awt.Font("SolaimanLipi", 0, 11));
        jLabel7.setText("মাস্টারমাইন্ড সাইবার সেন্টার ");
        jLabel7.setFont(new java.awt.Font("SolaimanLipi", 0, 36));
        jButton1.setText("সাইন ইন");
        jButton1.setFont(new java.awt.Font("SolaimanLipi", 0, 11));
        jButton2.setText("পিছনে");
        jButton2.setFont(new java.awt.Font("SolaimanLipi", 0, 11));
        jButton3.setText("নাম মুছুন ");
        jButton3.setFont(new java.awt.Font("SolaimanLipi", 0, 11));
    }

    public void English_signup() {
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // login_Database();
        if (jPasswordField3.getText().compareTo("mastermind") == 0 && jPasswordField1.getText().compareTo(jPasswordField2.getText()) == 0) {
            Connection con = null;
            String url = "jdbc:mysql://localhost:3306/";
            String db = "cyber_center";
            String driver = "com.mysql.jdbc.Driver";
            String user = "root";
            String pass = "";



            try {
                Class.forName(driver);
                con = (Connection) DriverManager.getConnection(url + db, user, pass);


                PreparedStatement st = (PreparedStatement) con.prepareStatement("INSERT INTO `cyber_center`.`login` (`username`, `password`, `con_password`) VALUES (?,?,?)");

                st.setString(1, jTextField1.getText());
                st.setString(2, jPasswordField1.getText());
                st.setString(3, jPasswordField2.getText());

                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "User account created seccessfully");

                jTextField1.setText("");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "This user name already exist, please insert another user name");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Invalid security code, please try again.", "Error", JOptionPane.ERROR_MESSAGE);     // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        hasib();
        if (jTextField1.getText().compareTo("" + str1) == 0 && jPasswordField1.getText().compareTo("" + str2) == 0 && jPasswordField2.getText().compareTo("" + str3) == 0) {

            String value = jTextField1.getText();
            Connection con = null;
            String url = "jdbc:mysql://localhost:3306/";
            String db = "cyber_center";
            String driver = "com.mysql.jdbc.Driver";
            String user = "root";
            String pass = "";


            try {
                Class.forName(driver);
                con = (Connection) DriverManager.getConnection(url + db, user, pass);
                PreparedStatement st = (PreparedStatement) con.prepareStatement("DELETE FROM `cyber_center`.`login` WHERE `username` = ?");
                st.setString(1, value);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Username is deleted successfully.");
                con.close();


                jTextField1.setText("");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error in deleting record, please try again.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "User name or password does not match? Please try again.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Sinup_window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
